theme = "ferra"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor]
mouse = true
cursorline = true
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"


[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "▶"
newline = "¬"
tabpad = " "

[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
