#!/bin/sh

# preconfigured git latexdiff


git latexdiff \
    -t CTRADITIONAL \
    --config="PICTUREENV=(?:picture|DIFnomarkup|align|cite|tabularx)[\w\d*@]*" \
    --exclude-safecmd=cite \
    --whole-tree \
    "$1"
