#!/bin/sh

# preconfigured git latexdiff


git latexdiff \
    --latexmk \
    --latexdiff-flatten \
    --type=CFONT \
    --whole-tree \
    --allow-spaces \
    --biber \
    --enable-citation-markup \
    --latexopt -shell-escape \
    "$1"
