#!/bin/sh

# Record the current running window name
wid=$(wmctrl -l -p | awk -v pid=$PPID '$3 == pid {print $1}')

mpv "$@" & 

timeout 10s bash -c -- "while true; do wmctrl -l | egrep -iq 'mpv' && break; sleep 0.1s; done"

wmctrl -i -a "$wid"
