#!/bin/sh

# todo use _getopts_ and bundle with _entr_

# My preferred settings for automatically converting a pandoc markdown document
# to pdf

# things to highlight here:
# resource: https://github.com/alexeygumirov/pandoc-beamer-how-to

DATE_COVER=$(date "+%d %B %Y")

# SOURCE_FORMAT="markdown_strict\
# +pipe_tables\
# +backtick_code_blocks\
# +auto_identifiers\
# +strikeout\
# +yaml_metadata_block\
# +implicit_figures\
# +all_symbols_escapable\
# +link_attributes\
# +smart\
# +fenced_divs"


pandoc $1 \
    --pdf-engine=xelatex \
    -t beamer \
    --template templates/cosmos.latex \
    --slide-level 2 \
    --highlight-style kate \
    --shift-heading-level=0 \
    --dpi 300 \
    -M date="$DATE_COVER" \
    -V 'fontsize=12pt' \
    -V 'classoption:aspectratio=169' \
    -o "${1%%.*}.pdf"
