#!/bin/sh

# ~/.xinitrc for dwl --- a wayland implementation of dwm

# Manually create XDG_RUNTIME_DIR since we are noting using a session manager
export XDG_RUNTIME_DIR=/tmp/xdg-runtime-$(id -u)
mkdir -p $XDG_RUNTIME_DIR

# Start dwl
exec dwl
