#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

function get_volume {
  pamixer --get-volume
}

function is_mute {
  pamixer --get-mute > /dev/null
}

function send_notification {
  volume=`get_volume`
  # Make the bar with the special character ─ (it's not dash -)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
  # Send the notification
  dunstify -i audio-volume-muted-blocking -t 500 -r 2593 -u normal "    $bar"
}

case $1 in
  up)
    pamixer -u  # unmute
    pamixer -i 2 > /dev/null
    send_notification
    ;;
  down)
    pamixer -u  # unmute
    pamixer -d 2 > /dev/null
    send_notification
    ;;
  mute)
    # Toggle mute
    pamixer -t
    if is_mute ; then
      dunstify -i audio-volume-muted -t 500 -r 2593 -u normal "Mute"
    else
      send_notification
    fi
    ;;
esac
