#!/bin/sh

setxkbmap -layout us -option 'caps:ctrl_modifier'
sxhkd &
setxkbmap -layout us -variant dvp -option 'caps:ctrl_modifier'

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width    2
bspc config window_gap      12

bspc config split_ratio     0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a mpv state=floating
bspc rule -a eletron state=floating
bspc rule -a feh state=floating


# Start up applications
/home/cosmos/.scripts/xcape.sh &
/home/cosmos/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore; sleep 1; compton -b
xfce4-power-manager
xautolock -time 10 -locker blurlock -corners -00- &
udiskie --tray &
dunst &
mpd &
pasystray &
/home/cosmos/.scripts/pomolaunch.sh &
syncthing-gtk &
nm-applet &
syncthing &
