#!/bin/sh

setxkbmap -layout us -option 'caps:ctrl_modifier'
sleep 1
setsid sxhkd -c /home/cosmos/.config/sxhkd/sxhkdrc-bspwm &
setxkbmap -layout us -variant dvp -option 'caps:ctrl_modifier'

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width    2
bspc config window_gap      12

bspc config split_ratio     0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a mpv state=floating
bspc rule -a eletron state=floating
bspc rule -a feh state=floating

# Start up applications
setsid /home/cosmos/Scripts/xcape.sh &
setsid /home/cosmos/Scripts/polylaunch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
setsid nitrogen --restore; sleep 1; picom -b &
setsid xfce4-power-manager &
# xautolock -time 10 -locker blurlock -corners -00- &
setsid udiskie --tray &
setsid dunst &
setsid mpd &
setsid xidlehook --not-when-audio --not-when-fullscreen --timer 600 "betterlockscreen -l blur" '' &
